// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const RESET_REGISTER_STATE = 'RESET_REGISTER_STATE';

// 1.Submissions
export const SUBMISSIONS_START = 'SUBMISSION_START';
export const SUBMISSIONS_ERROR = 'SUBMISSIONS_ERROR'; 
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_ALL_SUBMISSIONS_SUCCESS = 'GET_ALL_SUBMISSIONS_SUCCESS';
export const CREATE_SUBMISSION_SUCCESS = 'CREATE_SUBMISSION_SUCCESS';
export const RESET_CREATE_SUBMISSION_STATE = 'RESET_CREATE_SUBMISSION_STATE';
export const GET_SUBMISSIONS_BY_AUTHOR_SUCCESS = 'GET_SUBMISSIONS_BY_AUTHOR_SUCCESS';
export const GET_SUBMISSIONS_DETAIL_SUCCESS = 'GET_SUBMISSIONS_DETAIL_SUCCESS';
export const EDIT_SUBMISSION_SUCCESS = 'EDIT_SUBMISSION_SUCCESS';
export const RESET_EDIT_SUBMISSION_STATE = 'RESET_EDIT_SUBMISSION_STATE';
export const DELETE_SUBMISSION_SUCCESS = 'DELETE_SUBMISSION_SUCCESS'; 

// 2.Review Process
export const REVIEW_PROCESS_ERROR = 'REVIEW_PROCESS_ERROR';
// 2.1.Chief Editor
export const GET_ALL_EDITORS_SUCCESS = 'GET_ALL_EDITORS_SUCCESS'; 
export const ASSIGN_EDITOR_SUCCESS = 'ASSIGN_EDITOR_SUCCESS';
export const RESET_EDITOR_ASSIGNMENT_STATE = 'RESET_EDITOR_ASSIGNMENT_STATE';
export const GET_EDITOR_ASSIGNMENT_SUCCESS = 'GET_EDITOR_ASSIGNMENT_SUCCESS';
