// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const RESET_REGISTER_STATE = 'RESET_REGISTER_STATE';

// Submissions
export const SUBMISSIONS_START = 'SUBMISSION_START';
export const SUBMISSIONS_ERROR = 'SUBMISSIONS_ERROR'; 
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_ALL_SUBMISSIONS_SUCCESS = 'GET_ALL_SUBMISSIONS_SUCCESS';
export const CREATE_SUBMISSION_SUCCESS = 'CREATE_SUBMISSION_SUCCESS';
export const RESET_CREATE_SUBMISSION_STATE = 'RESET_CREATE_SUBMISSION_STATE';
export const GET_SUBMISSIONS_BY_AUTHOR_SUCCESS = 'GET_SUBMISSIONS_BY_AUTHOR_SUCCESS';
export const GET_SUBMISSIONS_DETAIL_SUCCESS = 'GET_SUBMISSIONS_DETAIL_SUCCESS';
